import EnglishContactForm from "./EnglishContactForm";
import { CmsOverride } from "./CmsPublic";
import { useEffect } from "react";
import { Link, useLocation } from "wouter";
import { ArrowUpRight, Mail, Menu } from "lucide-react";
import { useState } from "react";
const email = "bussneis.owner@gmail.com";
const logo = "/business-owner-transparent.png";
const services = [
 {slug:"strategy",label:"Business Strategy",kicker:"From idea to direction",description:"Clarify your offer, market position and priorities. Turn uncertainty into a practical 90-day roadmap.",points:["Market and offer diagnosis","90-day priorities","Decision metrics your team understands"]},
 {slug:"brand",label:"Brand Positioning & Offer",kicker:"Make your value clear",description:"Build positioning, messaging and a customer-focused offer that helps the right buyers understand why to choose you.",points:["Brand positioning","Sales-page messaging","Consistent visual communication"]},
 {slug:"growth",label:"Growth & Lead Generation",kicker:"From attention to qualified demand",description:"Connect useful content, conversion pages and lead capture into a measurable, repeatable growth system.",points:["Content strategy","Conversion journeys","Lead performance tracking"]},
];
const articles=[
 {slug:"growth-needs-a-system",category:"Business Growth",title:"Growth Needs a Clearer System, Not More Noise",excerpt:"Stop chasing every opportunity. Build a repeatable path that turns growth into an understandable result.",body:["Growth rarely becomes sustainable simply by increasing marketing activity. Without a defined customer, clear offer and reliable follow-up, additional traffic creates additional noise.","Start by identifying the audience you can serve best. Then connect a specific promise to a clear conversion path, from useful content to a meaningful conversation.","Measure qualified inquiries, conversion rates and the quality of follow-up. Improve the system one bottleneck at a time."]},
 {slug:"offer-before-logo",category:"Brand & Positioning",title:"Before Asking How Your Logo Looks, Ask What Customers Understand",excerpt:"A strong brand does more than look attractive. It reduces uncertainty and makes your value easier to grasp.",body:["Visual identity matters, but a polished logo cannot replace a clear commercial proposition. Your customer needs to know who you serve, what problem you solve and why your approach is different.","Begin with positioning, customer language and proof. Use design to reinforce that message rather than distract from it.","The best brand experience makes the next decision feel obvious, trustworthy and low-friction."]},
 {slug:"the-90-day-decision",category:"Management",title:"The 90-Day Decision: Choosing What Not to Do",excerpt:"A growth plan is not a wish list. It is the discipline to protect the few priorities that matter.",body:["Every business has more potential projects than it can execute well. A useful 90-day plan starts by choosing the outcome that matters most.","Define one measurable goal, the few initiatives most likely to move it and the activities you will deliberately postpone.","Review progress regularly. A good plan is not rigid; it is focused enough to reveal what is working."]},
];
const mail = (subject:string) => "mailto:"+email+"?subject="+encodeURIComponent(subject);
export default function EnglishSite(){
 const [path] = useLocation();
 const [menuOpen,setMenuOpen]=useState(false);
 useEffect(()=>{document.documentElement.lang="en";document.documentElement.dir="ltr";document.title="Business Owner | Business Strategy, Brand & Growth"; const canonical=document.querySelector<HTMLLinkElement>('link[rel="canonical"]');const previous=canonical?.href;if(canonical) canonical.href=window.location.origin+window.location.pathname;let meta=document.querySelector<HTMLMetaElement>('meta[name="description"]');const previousDescription=meta?.content;if(meta) meta.content="Business Owner provides business strategy, brand positioning, growth systems and practical insights for entrepreneurs and business owners.";return ()=>{document.documentElement.lang="ar";document.documentElement.dir="rtl";if(canonical&&previous)canonical.href=previous;if(meta&&previousDescription)meta.content=previousDescription;};},[]);
 const p=path.replace(/^\/en\/?/,"").replace(/\/$/,"");
 const service=p.startsWith("services/")?services.find(x=>x.slug===p.split("/")[1]):null;
 const article=p.startsWith("articles/")?articles.find(x=>x.slug===p.split("/")[1]):null;
 const title=(t:string)=> <div className="en-intro"><span className="en-eyebrow">BUSINESS OWNER</span><h1>{t}</h1></div>;
 const card=(label:string,description:string,href:string)=><Link href={href} className="en-card"><h3>{label}</h3><p>{description}</p><span>Explore <ArrowUpRight size={16}/></span></Link>;
 return <div className="en-site" lang="en" dir="ltr">
  <header className="en-header"><Link href="/en" className="en-logo"><img src={logo} alt="Business Owner" /></Link><button className="en-menu" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Toggle navigation"><Menu/></button><nav className={menuOpen?"en-nav is-open":"en-nav"} onClick={()=>setMenuOpen(false)}><Link href="/en">Home</Link><Link href="/en/services">Services</Link><Link href="/en/articles">Insights</Link><Link href="/en/about">About</Link><Link href="/en/contact">Contact</Link></nav><Link className="en-lang" href={p?"/"+p:"/"}>العربية</Link></header>
  <main><CmsOverride slug={p || "home"} locale="en">
  {!p && <><section className="en-hero"><div><span className="en-eyebrow">BUSINESS ADVISORY & GROWTH</span><h1>Great ideas need <em>clear direction.</em></h1><p>We help business owners turn experience into a compelling offer, a manageable growth system and content that earns trust before asking for a sale.</p><div className="en-actions"><a className="en-button" href={mail("Let's discuss my business")}>Discuss your business <ArrowUpRight size={18}/></a><Link href="/en/articles" className="en-text-link">Explore insights →</Link></div></div><div className="en-hero-image"><img src={logo} alt="Business Owner brand" /></div></section><section className="en-section"><span className="en-eyebrow">WHAT WE DO</span><h2>Build clarity. Create momentum.</h2><div className="en-grid">{services.map(x=><div key={x.slug}>{card(x.label,x.description,"/en/services/"+x.slug)}</div>)}</div></section><section className="en-section"><span className="en-eyebrow">LATEST INSIGHTS</span><h2>Ideas for better business decisions</h2><div className="en-grid">{articles.map(x=><div key={x.slug}>{card(x.title,x.excerpt,"/en/articles/"+x.slug)}</div>)}</div></section></>}
  {p==="services"&&<section className="en-section">{title("Services built around real business challenges")}<div className="en-grid">{services.map(x=><div key={x.slug}>{card(x.label,x.description,"/en/services/"+x.slug)}</div>)}</div></section>}
  {service&&<section className="en-section en-detail">{title(service.label)}<p className="en-lead">{service.description}</p><h2>What we work on</h2><ul>{service.points.map(x=><li key={x}>{x}</li>)}</ul><a className="en-button" href={mail("Inquiry: "+service.label)}>Discuss this service <Mail size={17}/></a></section>}
  {p==="articles"&&<section className="en-section">{title("Business insights & practical thinking")}<div className="en-grid">{articles.map(x=><div key={x.slug}>{card(x.title,x.excerpt,"/en/articles/"+x.slug)}</div>)}</div></section>}
  {article&&<article className="en-section en-detail">{title(article.title)}<p className="en-lead">{article.excerpt}</p>{article.body.map(x=><p key={x}>{x}</p>)}<a className="en-button" href={mail("Discuss: "+article.title)}>Turn this idea into action <ArrowUpRight size={17}/></a></article>}
  {p==="about"&&<section className="en-section en-detail">{title("About Business Owner")}<p className="en-lead">Business Owner is a practical knowledge and advisory platform for entrepreneurs, owners and decision-makers.</p><p>We believe that clarity is a competitive advantage. We connect business strategy, positioning, marketing and growth into decisions teams can execute.</p><p>Our approach is simple: understand, analyze, design, execute and improve.</p><a className="en-button" href={mail("Business Owner introduction")}>Get in touch <Mail size={17}/></a></section>}
  {p==="contact"&&<section className="en-section en-detail">{title("Let's talk about your business")}<p className="en-lead">Tell us what you are building or where you feel stuck. A short email is enough to start.</p><EnglishContactForm/><p>Or email us directly: <a href={"mailto:"+email}>{email}</a></p></section>}
  {p && !["services","articles","about","contact"].includes(p) && !service && !article && <section className="en-section en-detail">{title("Page not found")}<Link href="/en">Back to home</Link></section>}
  </CmsOverride></main><footer className="en-footer"><img src={logo} alt="Business Owner"/><p>Better decisions. Sustainable growth.</p><a href={"mailto:"+email}>{email}</a><Link href="/">العربية</Link></footer>
 </div>;
}
