import { useState } from "react";
import { trpc } from "./lib/trpc";
type Locale="ar"|"en";
type Kind="page"|"post";
type Section={id:string;type:"hero"|"text"|"image"|"embed"|"cta"|"faq";title?:string;body?:string;image?:string;alt?:string;url?:string;buttonLabel?:string;buttonUrl?:string};
type Editor={id?:number;contentKey:string;locale:Locale;slug:string;title:string;excerpt:string;body:string;summary:string;category:string;featuredImage:string;imageAlt:string;status:"draft"|"published";seoTitle:string;seoDescription:string;canonicalUrl:string;robots:"index,follow"|"noindex,follow"|"noindex,nofollow";ogImage:string;schemaJson:string;sections:Section[];embeds:{type:"video"|"iframe";url:string;title?:string}[]};
const blank=(locale:Locale="ar"):Editor=>({contentKey:"",locale,slug:"",title:"",excerpt:"",body:"",summary:"",category:"",featuredImage:"",imageAlt:"",status:"draft",seoTitle:"",seoDescription:"",canonicalUrl:"",robots:"index,follow",ogImage:"",schemaJson:"",sections:[],embeds:[]});
const nullable=(x:string)=>x.trim()||null;
export default function FullCMS(){
 const [tab,setTab]=useState<"dashboard"|"pages"|"posts"|"leads"|"settings">("dashboard");
 const [kind,setKind]=useState<Kind>("page");
 const [edit,setEdit]=useState<Editor|null>(null);
 const [settingKey,setSettingKey]=useState("site_name_ar");
 const [settingValue,setSettingValue]=useState("");
 const [message,setMessage]=useState("");
 const [uploading,setUploading]=useState(false);
 const utils=trpc.useUtils();
 const pages=trpc.cms.pages.useQuery();
 const posts=trpc.cms.posts.useQuery();
 const leads=trpc.admin.dashboard.useQuery();
 const settings=trpc.cms.settings.useQuery();
 const savePage=trpc.cms.savePage.useMutation({onSuccess:()=>{setMessage("تم حفظ الصفحة في قاعدة البيانات");utils.cms.pages.invalidate();},onError:e=>setMessage("تعذر الحفظ: "+e.message)});
 const savePost=trpc.cms.savePost.useMutation({onSuccess:()=>{setMessage("تم حفظ المقال في قاعدة البيانات");utils.cms.posts.invalidate();},onError:e=>setMessage("تعذر الحفظ: "+e.message)});
 const saveSetting=trpc.cms.saveSetting.useMutation({onSuccess:()=>{setMessage("تم حفظ الإعداد");utils.cms.settings.invalidate();},onError:e=>setMessage("تعذر الحفظ: "+e.message)});
 const deleteContent=trpc.cms.deleteContent.useMutation({onSuccess:()=>{setEdit(null);utils.cms.pages.invalidate();utils.cms.posts.invalidate();},onError:e=>setMessage(e.message)});
 const changeLead=trpc.admin.updateLeadStatus.useMutation({onSuccess:()=>utils.admin.dashboard.invalidate(),onError:e=>setMessage(e.message)});
 const logout=trpc.auth.logout.useMutation({onSuccess:()=>window.location.reload()});
 const set=(k:keyof Editor,v:any)=>setEdit(x=>x?{...x,[k]:v}:x);
 const uploadImage=async(file:File,target:"featuredImage"|"ogImage"|number)=>{
   if(!["image/png","image/jpeg","image/webp"].includes(file.type)||file.size>5*1024*1024){setMessage("الصورة يجب أن تكون JPG أو PNG أو WebP وأقل من 5MB");return;}
   setUploading(true);setMessage("");
   try{
     const response=await fetch("/api/admin/media",{method:"POST",credentials:"same-origin",headers:{"Content-Type":file.type},body:file});
     const data=await response.json();
     if(!response.ok||!data.url)throw new Error(data.error||"Upload failed");
     if(typeof target==="number")setEdit(current=>current?{...current,sections:current.sections.map((section,index)=>index===target?{...section,image:data.url}:section)}:current);
     else set(target,data.url);
     setMessage("تم رفع الصورة إلى مكتبة الوسائط");
   }catch(error){setMessage("فشل رفع الصورة: "+(error instanceof Error?error.message:String(error)));}
   finally{setUploading(false);}
 };
 const open=(k:Kind,item?:any)=>{setKind(k);setMessage("");setEdit(item?{...blank(item.locale),...item,featuredImage:item.featuredImage||"",imageAlt:item.imageAlt||"",seoTitle:item.seoTitle||"",seoDescription:item.seoDescription||"",canonicalUrl:item.canonicalUrl||"",ogImage:item.ogImage||"",schemaJson:item.schemaJson||"",excerpt:item.excerpt||"",body:item.body||"",summary:item.summary||"",category:item.category||"",sections:item.sections||[],embeds:item.embeds||[]}:blank());};
 const save=()=>{if(!edit)return;setMessage("");const common={id:edit.id,contentKey:edit.contentKey,locale:edit.locale,slug:edit.slug,title:edit.title,status:edit.status,featuredImage:nullable(edit.featuredImage),imageAlt:nullable(edit.imageAlt),seoTitle:nullable(edit.seoTitle),seoDescription:nullable(edit.seoDescription),canonicalUrl:nullable(edit.canonicalUrl),robots:edit.robots,ogImage:nullable(edit.ogImage),schemaJson:nullable(edit.schemaJson)};if(kind==="page")savePage.mutate({...common,summary:nullable(edit.summary),sections:edit.sections});else savePost.mutate({...common,excerpt:edit.excerpt,body:edit.body,category:nullable(edit.category),embeds:edit.embeds});};
 const input=(label:string,key:keyof Editor,rows=0)=><label className="cms-field"><span>{label}</span>{rows?<textarea rows={rows} value={String(edit?.[key]||"")} onChange={e=>set(key,e.target.value)}/>:<input value={String(edit?.[key]||"")} onChange={e=>set(key,e.target.value)}/>}</label>;
 const sections=edit?.sections||[];
 const updateSection=(i:number,k:keyof Section,v:string)=>set("sections",sections.map((s,j)=>i===j?{...s,[k]:v}:s));
 return <div className="full-cms" dir="rtl">
 <header className="cms-top"><div><strong>BUSINESS OWNER</strong><span>Content Management System</span></div><a href="/" target="_blank" rel="noreferrer">عرض الموقع ↗</a><button onClick={()=>logout.mutate()}>تسجيل خروج</button></header>
 <div className="cms-layout"><aside className="cms-side"><h3>لوحة الإدارة</h3>{([["dashboard","الرئيسية"],["pages","الصفحات"],["posts","المقالات"],["leads","طلبات العملاء"],["settings","إعدادات الموقع وSEO"]] as const).map(([k,label])=><button key={k} className={tab===k?"active":""} onClick={()=>{setTab(k);setEdit(null);setMessage("");}}>{label}</button>)}</aside>
 <main className="cms-main">{message&&<div className="cms-message" role="status">{message}</div>}
 {tab==="dashboard"&&!edit&&<><h1>نظرة عامة</h1><div className="cms-metrics"><div><span>الصفحات</span><strong>{pages.data?.length??"—"}</strong></div><div><span>المقالات</span><strong>{posts.data?.length??"—"}</strong></div><div><span>طلبات العملاء</span><strong>{leads.data?.leads.length??"—"}</strong></div></div><p>الأرقام تُقرأ مباشرة من قاعدة البيانات، ولا توجد بيانات تجريبية.</p></>}
 {(tab==="pages"||tab==="posts")&&!edit&&<><div className="cms-heading"><h1>{tab==="pages"?"إدارة الصفحات":"إدارة المقالات"}</h1><button className="cms-primary" onClick={()=>open(tab==="pages"?"page":"post")}>+ إضافة {tab==="pages"?"صفحة":"مقال"}</button></div><p>المحتوى العربي والإنجليزي منفصل لكل لغة، ومربوط بمفتاح محتوى واحد.</p><div className="cms-table">{(tab==="pages"?pages.data:posts.data)?.map(item=><div key={item.id} className="cms-table-row"><div><strong>{item.title}</strong><small>{item.locale.toUpperCase()} · /{item.slug} · {item.status}</small></div><button onClick={()=>open(tab==="pages"?"page":"post",item)}>تعديل</button></div>)}</div>{(tab==="pages"?pages:posts).isError&&<p className="cms-error">تعذر تحميل المحتوى: {(tab==="pages"?pages:posts).error?.message}</p>}</>}
 {edit&&<><div className="cms-heading"><h1>{edit.id?"تعديل":"إضافة"} {kind==="page"?"صفحة":"مقال"}</h1><button onClick={()=>setEdit(null)}>رجوع للقائمة</button></div><div className="cms-edit-grid"><div className="cms-edit-main">
 <section className="cms-panel"><h2>المحتوى الأساسي</h2><div className="cms-inline"><label className="cms-field"><span>اللغة</span><select value={edit.locale} onChange={e=>set("locale",e.target.value)}><option value="ar">العربية</option><option value="en">English</option></select></label><label className="cms-field"><span>الحالة</span><select value={edit.status} onChange={e=>set("status",e.target.value)}><option value="draft">مسودة</option><option value="published">منشور</option></select></label></div>{input("Content Key — نفس المفتاح للترجمة","contentKey")}{input("Slug","slug")}{input("العنوان","title")}{kind==="post"?<>{input("الوصف المختصر","excerpt",3)}{input("المحتوى — نص المقال","body",12)}{input("التصنيف","category")}</>:<>{input("مقدمة الصفحة","summary",3)}<h3>أقسام الصفحة (Page Builder)</h3>{sections.map((section,i)=><div className="cms-section" key={section.id}><div className="cms-heading"><strong>القسم {i+1}</strong><button onClick={()=>set("sections",sections.filter((_,j)=>j!==i))}>حذف</button></div><label className="cms-field"><span>نوع القسم</span><select value={section.type} onChange={e=>updateSection(i,"type",e.target.value)}>{["hero","text","image","embed","cta","faq"].map(x=><option key={x} value={x}>{x}</option>)}</select></label>{(["title","body","image","alt","url","buttonLabel","buttonUrl"] as const).map(k=><label className="cms-field" key={k}><span>{k}</span><input value={section[k]||""} onChange={e=>updateSection(i,k,e.target.value)}/></label>)}<label className="cms-field"><span>رفع صورة لهذا القسم (JPG / PNG / WebP)</span><input type="file" accept="image/jpeg,image/png,image/webp" disabled={uploading} onChange={e=>{const file=e.target.files?.[0];if(file)void uploadImage(file,i);}}/></label>{section.image&&<img className="cms-image-preview" src={section.image} alt={section.alt||section.title||"Section preview"}/>}</div>)}<button onClick={()=>set("sections",[...sections,{id:"section-"+Date.now(),type:"text",title:"",body:""}])}>+ إضافة Section</button></>}</section>
 <section className="cms-panel"><h2>الصور والوسائط</h2>{input("رابط صورة الغلاف HTTPS","featuredImage")}<label className="cms-field"><span>رفع صورة من جهازك (JPG / PNG / WebP — حتى 5MB)</span><input type="file" accept="image/jpeg,image/png,image/webp" disabled={uploading} onChange={e=>{const file=e.target.files?.[0];if(file)void uploadImage(file,"featuredImage");}}/>{uploading&&<small>جاري رفع الصورة...</small>}</label>{input("وصف الصورة ALT","imageAlt")}{edit.featuredImage&&<img className="cms-image-preview" src={edit.featuredImage} alt={edit.imageAlt||"Preview"}/>}
 {kind==="post"&&<><h3>Embedded Media</h3>{edit.embeds.map((e,i)=><div className="cms-inline" key={i}><input placeholder="HTTPS Embed URL" value={e.url} onChange={event=>set("embeds",edit.embeds.map((v,j)=>i===j?{...v,url:event.target.value}:v))}/><button onClick={()=>set("embeds",edit.embeds.filter((_,j)=>j!==i))}>حذف</button></div>)}<button onClick={()=>set("embeds",[...edit.embeds,{type:"iframe",url:""}])}>+ إضافة Embed</button><small>روابط YouTube وVimeo وGoogle Maps وFigma المسموح بها فقط.</small></>}</section>
 </div><aside className="cms-edit-side"><section className="cms-panel"><h2>SEO الخاص بالمحتوى</h2>{input("SEO Title","seoTitle")}{input("Meta Description","seoDescription",3)}{input("Canonical URL","canonicalUrl")}{input("Open Graph Image","ogImage")}{input("JSON-LD Schema","schemaJson",6)}<label className="cms-field"><span>Robots</span><select value={edit.robots} onChange={e=>set("robots",e.target.value)}>{["index,follow","noindex,follow","noindex,nofollow"].map(x=><option key={x}>{x}</option>)}</select></label></section><section className="cms-panel"><button className="cms-primary cms-full" disabled={savePage.isPending||savePost.isPending} onClick={save}>حفظ {edit.status==="published"?"ونشر":"كمسودة"}</button>{edit.id&&<button className="cms-danger cms-full" onClick={()=>{if(window.confirm("حذف المحتوى نهائيًا؟"))deleteContent.mutate({kind,id:edit.id!});}}>حذف نهائي</button>}</section></aside></div></>}
 {tab==="leads"&&!edit&&<><h1>طلبات العملاء (Contact Us)</h1><p>جميع الطلبات الفعلية المسجلة في قاعدة البيانات.</p><div className="cms-table">{leads.data?.leads.map(x=><div className="cms-table-row" key={x.id}><div><strong>{x.name} — {x.company||"عميل"}</strong><small><a href={"mailto:"+x.email}>{x.email}</a> · {x.service||"عام"} · {new Date(x.createdAt).toLocaleString("ar-SA")}</small><p>{x.message}</p></div><select value={x.status} onChange={e=>changeLead.mutate({id:x.id,status:e.target.value as "new"|"contacted"|"closed"})}><option value="new">جديد</option><option value="contacted">تم التواصل</option><option value="closed">مغلق</option></select></div>)}</div>{leads.isError&&<p className="cms-error">{leads.error.message}</p>}</>}
 {tab==="settings"&&!edit&&<><h1>الإعدادات العامة وSEO وGoogle Search Console</h1><div className="cms-panel"><p>اختر إعدادًا وعدّل قيمته. تُحفظ القيم في قاعدة البيانات؛ تفعيلها على الواجهة يحتاج ربط قوالب العرض.</p><label className="cms-field"><span>الإعداد</span><select value={settingKey} onChange={e=>{setSettingKey(e.target.value);setSettingValue(settings.data?.find(x=>x.key===e.target.value)?.value||"");}}>{[["site_name_ar","اسم الموقع عربي"],["site_name_en","اسم الموقع English"],["site_description_ar","وصف الموقع عربي"],["site_description_en","وصف الموقع English"],["default_og_image","الصورة الافتراضية للمشاركة"],["google_site_verification","GSC Meta Verification"],["gsc_verification_file_name","اسم ملف Google Verification"],["gsc_verification_file_content","محتوى ملف Google Verification"],["robots_txt","Robots.txt"],["head_embed","Head Embed"],["footer_embed","Footer Embed"]].map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label><label className="cms-field"><span>القيمة</span><textarea rows={7} value={settingValue} onChange={e=>setSettingValue(e.target.value)}/></label><button className="cms-primary" onClick={()=>saveSetting.mutate({key:settingKey as any,value:settingValue})}>حفظ الإعداد</button><div className="cms-table">{settings.data?.map(x=><button className="cms-table-row" key={x.key} onClick={()=>{setSettingKey(x.key);setSettingValue(x.value)}}><strong>{x.key}</strong><small>تعديل</small></button>)}</div></div></>}
 </main></div></div>;
}
